name: Build

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'


      - name: Install
        run: npm install
      - name: Build 
        run: npm run build:prod

      - uses: actions/cache@v2
        id: restore-dependencies-cache
        with:
          path: |
            node_modules
          key: dependencies-${{ github.sha }}
  
  test:
    name: Test Project
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - uses: actions/cache@v2
        id: restore-dependencies-cache
        with:
          path: |
            node_modules
          key: dependencies-${{ github.sha }}
      - name: Run tests
        working-directory: server
        run: npm run test

  deploy:
    name: Deploy
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - uses: actions/cache@v2
        id: restore-dependencies-cache
        with:
          path: |
            node_modules
          key: dependencies-${{ github.sha }}

      - name: Log in to Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: tbhanson96
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build image
        run: npm run package
      
      - run: docker image tag docker-starter:latest ghcr.io/tbhanson96/docker-starter:latest
      - run: docker image push ghcr.io/tbhanson96/docker-starter:latest
